### ISSUE TITLE
Sun Component

### ISSUE THREAD

**Issue by milafrerichs** [milafrerichs/map-reduce-game#12]
Props:
* month name
* two colors
* arc angle

Depending on the month provided have a new point (svg of a sun) on an arc
And also different colors for the svg
The arc needs to be configurable 

## Acceptance criteria
Providing a month name, two colors and an arc angle
The component Redners a sun on an arc 
With the first color being the inner sun color and the second color the outer sun
The sun will be on a position depending the month (we might change this to arc angle in a iteration)
Early in the year on the left side
Summer in the middle and late in the year on the right side

![sun-svgrepo-com](https://user-images.githubusercontent.com/688980/152735263-4a6e25de-cd29-4d94-975a-cdcc2e5fd85c.svg)

**Comment by yspringfield** [comment]
I don't understand this part.

> The sun will be on a position depending the month (we might change this to arc angle in a iteration)
Early in the year on the left side

Could you create a small visual showing the approximate position of the sun in january, june and december. That'll be great.
